/*
 * Copyright 2026 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef __CANNED_GESTURE_CLASSIFIER_I8_OPT_TFLITE_INFO_H__
#define __CANNED_GESTURE_CLASSIFIER_I8_OPT_TFLITE_INFO_H__

#define CANNED_GESTURE_CLASSIFIER_NAME "canned_gesture_classifier"

#define GESTURE_CLASSIFIER_SCORE_OUTPUT_IDX     0

#define GESTURE_CLASSIFIER_OUTPUT_SIZE          8
#define GESTURE_CLASSIFIER_MAX_LABEL_LENGTH     32

#endif /* __CANNED_GESTURE_CLASSIFIER_I8_OPT_TFLITE_INFO_H__ */