/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef _SCRFD_KPS_500M_320X256_TFLITE_INFO_H_
#define _SCRFD_KPS_500M_320X256_TFLITE_INFO_H_

#define SCRFD_KPS_NAME "scrfd_kps_500m"
/* mean and std will be used to get input values in the model input data range.
 * for SCRFD data should be between 0 and 1. */
#define SCRFD_KPS_INPUT_MEAN   0
#define SCRFD_KPS_INPUT_STD    255
#define SCRFD_KPS_WIDTH        320
#define SCRFD_KPS_HEIGHT       256
#define SCRFD_KPS_PIXEL_FORMAT MPP_PIXEL_RGB

// number of boxes at each stride level
#define SCRFD_KPS_OUTPUT_NUM_BOXES_SMALL  2560
#define SCRFD_KPS_OUTPUT_NUM_BOXES_MEDIUM 640
#define SCRFD_KPS_OUTPUT_NUM_BOXES_LARGE  160
#define SCRFD_KPS_MAX_POINTS (SCRFD_KPS_OUTPUT_NUM_BOXES_SMALL + SCRFD_KPS_OUTPUT_NUM_BOXES_MEDIUM + SCRFD_KPS_OUTPUT_NUM_BOXES_LARGE)

// strides at each output level
#define SCRFD_KPS_STRIDE_SMALL   8
#define SCRFD_KPS_STRIDE_MEDIUM  16
#define SCRFD_KPS_STRIDE_LARGE   32

// number of landmarks for each detected box
#define SCRFD_NUM_LANDMARKS 5

/* SCRFD_KPS_OUTPUT_SCALE and SCRFD_KPS_OUTPUT_ZERO_POINT are the model quantization parameters
 * and can be found by visualizing the model using netron */

// scales and zero points for scores
#define SCRFD_KPS_OUTPUT_SCORE_SMALL_SCALE       0.00390625f
#define SCRFD_KPS_OUTPUT_SCORE_SMALL_ZERO_POINT  0.0f
#define SCRFD_KPS_OUTPUT_SCORE_MEDIUM_SCALE      0.00390625f
#define SCRFD_KPS_OUTPUT_SCORE_MEDIUM_ZERO_POINT 0.0f
#define SCRFD_KPS_OUTPUT_SCORE_LARGE_SCALE       0.00390625f
#define SCRFD_KPS_OUTPUT_SCORE_LARGE_ZERO_POINT  0.0f

// scales and zero points for boxes
#define SCRFD_KPS_OUTPUT_BOXES_SMALL_SCALE       0.019342631101608276f
#define SCRFD_KPS_OUTPUT_BOXES_SMALL_ZERO_POINT  3.0f
#define SCRFD_KPS_OUTPUT_BOXES_MEDIUM_SCALE      0.01798337884247303f
#define SCRFD_KPS_OUTPUT_BOXES_MEDIUM_ZERO_POINT 0.0f
#define SCRFD_KPS_OUTPUT_BOXES_LARGE_SCALE       0.015552294440567493f
#define SCRFD_KPS_OUTPUT_BOXES_LARGE_ZERO_POINT  0.0f

// scales and zero points for landmarks
#define SCRFD_KPS_OUTPUT_KPS_SMALL_SCALE       0.02315187081694603f
#define SCRFD_KPS_OUTPUT_KPS_SMALL_ZERO_POINT  117.0f
#define SCRFD_KPS_OUTPUT_KPS_MEDIUM_SCALE      0.02257261797785759f
#define SCRFD_KPS_OUTPUT_KPS_MEDIUM_ZERO_POINT 117.0f
#define SCRFD_KPS_OUTPUT_KPS_LARGE_SCALE       0.018106726929545403f
#define SCRFD_KPS_OUTPUT_KPS_LARGE_ZERO_POINT  129.0f

#define SCRFD_KPS_TENSOR_IDX_KPS_SMALL     0
#define SCRFD_KPS_TENSOR_IDX_SCORE_SMALL   1  
#define SCRFD_KPS_TENSOR_IDX_BOX_SMALL     2
#define SCRFD_KPS_TENSOR_IDX_KPS_LARGE     3
#define SCRFD_KPS_TENSOR_IDX_SCORE_LARGE   4
#define SCRFD_KPS_TENSOR_IDX_BOX_LARGE     5
#define SCRFD_KPS_TENSOR_IDX_SCORE_MEDIUM  6
#define SCRFD_KPS_TENSOR_IDX_BOX_MEDIUM    7
#define SCRFD_KPS_TENSOR_IDX_KPS_MEDIUM    8

#endif /* _SCRFD_KPS_500M_320X256_TFLITE_INFO_H_ */
