/*
 * Copyright 2026 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef __HAND_LANDMARK_QUANT_INT8_TFLITE_INFO_H__
#define __HAND_LANDMARK_QUANT_INT8_TFLITE_INFO_H__

#define HAND_LANGMARK_NAME "hand_landmark"
/* mean and std will be used to get input values in the model input data range.
 * for SCRFD data should be between 0 and 1. */
#define HAND_LANDMARK_INPUT_MEAN   0
#define HAND_LANDMARK_INPUT_STD    255
#define HAND_LANDMARK_WIDTH        224
#define HAND_LANDMARK_HEIGHT       224
#define HAND_LANDMARK_PIXEL_FORMAT MPP_PIXEL_RGB

#define HAND_LANDMARK_LEFT_HAND_SCALE           0.00390625f
#define HAND_LANDMARK_LEFT_HAND_ZERO_POINT     -128.0f
#define HAND_LANDMARK_GLOBAL_KP_SCALE           1.2440930604934692f
#define HAND_LANDMARK_GLOBAL_KP_ZERO_POINT     -69.0f
#define HAND_LANDMARK_HAS_HAND_SCALE            0.00390625f
#define HAND_LANDMARK_HAS_HAND_ZERO_POINT      -128.0f
#define HAND_LANDMARK_RELATIVE_KP_SCALE         0.0007785363704897463f
#define HAND_LANDMARK_RELATIVE_KP_ZERO_POINT   -11.0f

#define HAND_LANDMARK_LEFT_HAND_OUTPUT_IDX      0
#define HAND_LANDMARK_RELATIVE_KP_OUTPUT_IDX    1
#define HAND_LANDMARK_HAS_HAND_OUTPUT_IDX       2
#define HAND_LANDMARK_GLOBAL_KP_OUTPUT_IDX      3

#define HAND_LANDMARK_NUM_LANDMARKS             21

#define HAND_LANDMARK_HAS_HAND_THRESHOLD        0.6f
#define HAND_LANDMARK_LEFT_HAND_THRESHOLD       0.5f

#endif /* __HAND_LANDMARK_QUANT_INT8_TFLITE_INFO_H__ */