#!/usr/bin/expect -f

# timeout duration is seconds
set timeout 30
# uart device name
set uart "/dev/ttyACM0"
# uart baud rate
set baud "115200"
# board model
set board "rt1170"

set elfimg [lindex $argv 0]
set board [lindex $argv 1]
set imgname [exec basename $elfimg]
spawn -open [open $uart w+]
stty ispeed $baud ospeed $baud \
    raw -echo cs8 -parenb -cstopb -onlcr < $uart

log_user 0
system LinkServer flash $board load $elfimg  2>&1 >/dev/null

set green "\033\[0;32m"
set red "\033\[1;31m"
set yellow "\033\[1;33m"
set normal "\033\[0;0m"

expect {
    "TEST PASS" {
        send_user "${green}PASSED\n"
    }
    "TEST FAIL" {
        send_user "${red}FAILED\n"
    }
    "ERR:" {
        send_user "${red}ERROR\n"
    }
    -nocase "error" {
        send_user "${red}ERROR\n"
    }
    timeout {
        send_user "${yellow}TIMEOUT\n"
    }
}
send_user "${normal}"

